<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE eagle SYSTEM "eagle.dtd">
<eagle version="9.6.2">
<drawing>
<settings>
<setting alwaysvectorfont="no"/>
<setting verticaltext="up"/>
</settings>
<grid distance="0.1" unitdist="inch" unit="inch" style="lines" multiple="1" display="no" altdistance="0.01" altunitdist="inch" altunit="inch"/>
<layers>
<layer number="1" name="Top" color="4" fill="1" visible="no" active="no"/>
<layer number="16" name="Bottom" color="1" fill="1" visible="no" active="no"/>
<layer number="17" name="Pads" color="2" fill="1" visible="no" active="no"/>
<layer number="18" name="Vias" color="2" fill="1" visible="no" active="no"/>
<layer number="19" name="Unrouted" color="6" fill="1" visible="no" active="no"/>
<layer number="20" name="Dimension" color="15" fill="1" visible="no" active="no"/>
<layer number="21" name="tPlace" color="7" fill="1" visible="no" active="no"/>
<layer number="22" name="bPlace" color="7" fill="1" visible="no" active="no"/>
<layer number="23" name="tOrigins" color="15" fill="1" visible="no" active="no"/>
<layer number="24" name="bOrigins" color="15" fill="1" visible="no" active="no"/>
<layer number="25" name="tNames" color="7" fill="1" visible="no" active="no"/>
<layer number="26" name="bNames" color="7" fill="1" visible="no" active="no"/>
<layer number="27" name="tValues" color="7" fill="1" visible="no" active="no"/>
<layer number="28" name="bValues" color="7" fill="1" visible="no" active="no"/>
<layer number="29" name="tStop" color="7" fill="3" visible="no" active="no"/>
<layer number="30" name="bStop" color="7" fill="6" visible="no" active="no"/>
<layer number="31" name="tCream" color="7" fill="4" visible="no" active="no"/>
<layer number="32" name="bCream" color="7" fill="5" visible="no" active="no"/>
<layer number="33" name="tFinish" color="6" fill="3" visible="no" active="no"/>
<layer number="34" name="bFinish" color="6" fill="6" visible="no" active="no"/>
<layer number="35" name="tGlue" color="7" fill="4" visible="no" active="no"/>
<layer number="36" name="bGlue" color="7" fill="5" visible="no" active="no"/>
<layer number="37" name="tTest" color="7" fill="1" visible="no" active="no"/>
<layer number="38" name="bTest" color="7" fill="1" visible="no" active="no"/>
<layer number="39" name="tKeepout" color="4" fill="11" visible="no" active="no"/>
<layer number="40" name="bKeepout" color="1" fill="11" visible="no" active="no"/>
<layer number="41" name="tRestrict" color="4" fill="10" visible="no" active="no"/>
<layer number="42" name="bRestrict" color="1" fill="10" visible="no" active="no"/>
<layer number="43" name="vRestrict" color="2" fill="10" visible="no" active="no"/>
<layer number="44" name="Drills" color="7" fill="1" visible="no" active="no"/>
<layer number="45" name="Holes" color="7" fill="1" visible="no" active="no"/>
<layer number="46" name="Milling" color="3" fill="1" visible="no" active="no"/>
<layer number="47" name="Measures" color="7" fill="1" visible="no" active="no"/>
<layer number="48" name="Document" color="7" fill="1" visible="no" active="no"/>
<layer number="49" name="Reference" color="7" fill="1" visible="no" active="no"/>
<layer number="51" name="tDocu" color="6" fill="9" visible="no" active="no"/>
<layer number="52" name="bDocu" color="7" fill="1" visible="no" active="no"/>
<layer number="88" name="SimResults" color="9" fill="1" visible="yes" active="yes"/>
<layer number="89" name="SimProbes" color="9" fill="1" visible="yes" active="yes"/>
<layer number="90" name="Modules" color="5" fill="1" visible="yes" active="yes"/>
<layer number="91" name="Nets" color="2" fill="1" visible="yes" active="yes"/>
<layer number="92" name="Busses" color="1" fill="1" visible="yes" active="yes"/>
<layer number="93" name="Pins" color="2" fill="1" visible="no" active="yes"/>
<layer number="94" name="Symbols" color="4" fill="1" visible="yes" active="yes"/>
<layer number="95" name="Names" color="7" fill="1" visible="yes" active="yes"/>
<layer number="96" name="Values" color="7" fill="1" visible="yes" active="yes"/>
<layer number="97" name="Info" color="7" fill="1" visible="yes" active="yes"/>
<layer number="98" name="Guide" color="6" fill="1" visible="yes" active="yes"/>
</layers>
<schematic xreflabel="%F%N/%S.%C%R" xrefpart="/%S.%C%R">
<libraries>
<library name="xilinx-xcv" urn="urn:adsk.eagle:library:417">
<description>&lt;b&gt;XILINX Virtex?-E 1.8 V Field Programmable Gate Arrays&lt;/b&gt;&lt;p&gt;
http://www.xilinx.com&lt;br&gt;
&lt;author&gt;Created by librarian@cadsoft.de&lt;/author&gt;&lt;p&gt;</description>
<packages>
<package name="BG256" library_version="1">
<description>&lt;b&gt;xcv100_bg256_1532&lt;/b&gt; &lt;font color="red"&gt;edit this description&lt;/font&gt;&lt;p&gt;
Auto generated by &lt;i&gt;make-symbol-device-package-bsdl.ulp Rev. 25&lt;/i&gt;&lt;br&gt;
Source: xcv100_bg256_1532.bsd</description>
<wire x1="-13.3984" y1="-13.3984" x2="13.3984" y2="-13.3984" width="0.2032" layer="21"/>
<wire x1="13.3984" y1="-13.3984" x2="13.3984" y2="13.3984" width="0.2032" layer="21"/>
<wire x1="13.3984" y1="13.3984" x2="-12.23" y2="13.3984" width="0.2032" layer="21"/>
<wire x1="-13.3984" y1="12.23" x2="-13.3984" y2="-13.3984" width="0.2032" layer="21"/>
<wire x1="-13.3984" y1="12.23" x2="-12.23" y2="13.3984" width="0.2032" layer="21"/>
<circle x="12.065" y="-12.065" radius="0.4" width="0" layer="29"/>
<circle x="10.795" y="-12.065" radius="0.4" width="0" layer="29"/>
<circle x="9.525" y="-12.065" radius="0.4" width="0" layer="29"/>
<circle x="8.255" y="-12.065" radius="0.4" width="0" layer="29"/>
<circle x="6.985" y="-12.065" radius="0.4" width="0" layer="29"/>
<circle x="5.715" y="-12.065" radius="0.4" width="0" layer="29"/>
<circle x="4.445" y="-12.065" radius="0.4" width="0" layer="29"/>
<circle x="3.175" y="-12.065" radius="0.4" width="0" layer="29"/>
<circle x="1.905" y="-12.065" radius="0.4" width="0" layer="29"/>
<circle x="0.635" y="-12.065" radius="0.4" width="0" layer="29"/>
<circle x="-0.635" y="-12.065" radius="0.4" width="0" layer="29"/>
<circle x="-1.905" y="-12.065" radius="0.4" width="0" layer="29"/>
<circle x="-3.175" y="-12.065" radius="0.4" width="0" layer="29"/>
<circle x="-4.445" y="-12.065" radius="0.4" width="0" layer="29"/>
<circle x="-5.715" y="-12.065" radius="0.4" width="0" layer="29"/>
<circle x="-6.985" y="-12.065" radius="0.4" width="0" layer="29"/>
<circle x="-8.255" y="-12.065" radius="0.4" width="0" layer="29"/>
<circle x="-9.525" y="-12.065" radius="0.4" width="0" layer="29"/>
<circle x="-10.795" y="-12.065" radius="0.4" width="0" layer="29"/>
<circle x="-12.065" y="-12.065" radius="0.4" width="0" layer="29"/>
<circle x="12.065" y="-10.795" radius="0.4" width="0" layer="29"/>
<circle x="10.795" y="-10.795" radius="0.4" width="0" layer="29"/>
<circle x="9.525" y="-10.795" radius="0.4" width="0" layer="29"/>
<circle x="8.255" y="-10.795" radius="0.4" width="0" layer="29"/>
<circle x="6.985" y="-10.795" radius="0.4" width="0" layer="29"/>
<circle x="5.715" y="-10.795" radius="0.4" width="0" layer="29"/>
<circle x="4.445" y="-10.795" radius="0.4" width="0" layer="29"/>
<circle x="3.175" y="-10.795" radius="0.4" width="0" layer="29"/>
<circle x="1.905" y="-10.795" radius="0.4" width="0" layer="29"/>
<circle x="0.635" y="-10.795" radius="0.4" width="0" layer="29"/>
<circle x="-0.635" y="-10.795" radius="0.4" width="0" layer="29"/>
<circle x="-1.905" y="-10.795" radius="0.4" width="0" layer="29"/>
<circle x="-3.175" y="-10.795" radius="0.4" width="0" layer="29"/>
<circle x="-4.445" y="-10.795" radius="0.4" width="0" layer="29"/>
<circle x="-5.715" y="-10.795" radius="0.4" width="0" layer="29"/>
<circle x="-6.985" y="-10.795" radius="0.4" width="0" layer="29"/>
<circle x="-8.255" y="-10.795" radius="0.4" width="0" layer="29"/>
<circle x="-9.525" y="-10.795" radius="0.4" width="0" layer="29"/>
<circle x="-10.795" y="-10.795" radius="0.4" width="0" layer="29"/>
<circle x="-12.065" y="-10.795" radius="0.4" width="0" layer="29"/>
<circle x="12.065" y="-9.525" radius="0.4" width="0" layer="29"/>
<circle x="10.795" y="-9.525" radius="0.4" width="0" layer="29"/>
<circle x="9.525" y="-9.525" radius="0.4" width="0" layer="29"/>
<circle x="8.255" y="-9.525" radius="0.4" width="0" layer="29"/>
<circle x="6.985" y="-9.525" radius="0.4" width="0" layer="29"/>
<circle x="5.715" y="-9.525" radius="0.4" width="0" layer="29"/>
<circle x="4.445" y="-9.525" radius="0.4" width="0" layer="29"/>
<circle x="3.175" y="-9.525" radius="0.4" width="0" layer="29"/>
<circle x="1.905" y="-9.525" radius="0.4" width="0" layer="29"/>
<circle x="0.635" y="-9.525" radius="0.4" width="0" layer="29"/>
<circle x="-0.635" y="-9.525" radius="0.4" width="0" layer="29"/>
<circle x="-1.905" y="-9.525" radius="0.4" width="0" layer="29"/>
<circle x="-3.175" y="-9.525" radius="0.4" width="0" layer="29"/>
<circle x="-4.445" y="-9.525" radius="0.4" width="0" layer="29"/>
<circle x="-5.715" y="-9.525" radius="0.4" width="0" layer="29"/>
<circle x="-6.985" y="-9.525" radius="0.4" width="0" layer="29"/>
<circle x="-8.255" y="-9.525" radius="0.4" width="0" layer="29"/>
<circle x="-9.525" y="-9.525" radius="0.4" width="0" layer="29"/>
<circle x="-10.795" y="-9.525" radius="0.4" width="0" layer="29"/>
<circle x="-12.065" y="-9.525" radius="0.4" width="0" layer="29"/>
<circle x="12.065" y="-8.255" radius="0.4" width="0" layer="29"/>
<circle x="10.795" y="-8.255" radius="0.4" width="0" layer="29"/>
<circle x="9.525" y="-8.255" radius="0.4" width="0" layer="29"/>
<circle x="8.255" y="-8.255" radius="0.4" width="0" layer="29"/>
<circle x="6.985" y="-8.255" radius="0.4" width="0" layer="29"/>
<circle x="5.715" y="-8.255" radius="0.4" width="0" layer="29"/>
<circle x="4.445" y="-8.255" radius="0.4" width="0" layer="29"/>
<circle x="3.175" y="-8.255" radius="0.4" width="0" layer="29"/>
<circle x="1.905" y="-8.255" radius="0.4" width="0" layer="29"/>
<circle x="0.635" y="-8.255" radius="0.4" width="0" layer="29"/>
<circle x="-0.635" y="-8.255" radius="0.4" width="0" layer="29"/>
<circle x="-1.905" y="-8.255" radius="0.4" width="0" layer="29"/>
<circle x="-3.175" y="-8.255" radius="0.4" width="0" layer="29"/>
<circle x="-4.445" y="-8.255" radius="0.4" width="0" layer="29"/>
<circle x="-5.715" y="-8.255" radius="0.4" width="0" layer="29"/>
<circle x="-6.985" y="-8.255" radius="0.4" width="0" layer="29"/>
<circle x="-8.255" y="-8.255" radius="0.4" width="0" layer="29"/>
<circle x="-9.525" y="-8.255" radius="0.4" width="0" layer="29"/>
<circle x="-10.795" y="-8.255" radius="0.4" width="0" layer="29"/>
<circle x="-12.065" y="-8.255" radius="0.4" width="0" layer="29"/>
<circle x="12.065" y="-6.985" radius="0.4" width="0" layer="29"/>
<circle x="10.795" y="-6.985" radius="0.4" width="0" layer="29"/>
<circle x="9.525" y="-6.985" radius="0.4" width="0" layer="29"/>
<circle x="8.255" y="-6.985" radius="0.4" width="0" layer="29"/>
<circle x="-8.255" y="-6.985" radius="0.4" width="0" layer="29"/>
<circle x="-9.525" y="-6.985" radius="0.4" width="0" layer="29"/>
<circle x="-10.795" y="-6.985" radius="0.4" width="0" layer="29"/>
<circle x="-12.065" y="-6.985" radius="0.4" width="0" layer="29"/>
<circle x="12.065" y="-5.715" radius="0.4" width="0" layer="29"/>
<circle x="10.795" y="-5.715" radius="0.4" width="0" layer="29"/>
<circle x="9.525" y="-5.715" radius="0.4" width="0" layer="29"/>
<circle x="8.255" y="-5.715" radius="0.4" width="0" layer="29"/>
<circle x="-8.255" y="-5.715" radius="0.4" width="0" layer="29"/>
<circle x="-9.525" y="-5.715" radius="0.4" width="0" layer="29"/>
<circle x="-10.795" y="-5.715" radius="0.4" width="0" layer="29"/>
<circle x="-12.065" y="-5.715" radius="0.4" width="0" layer="29"/>
<circle x="12.065" y="-4.445" radius="0.4" width="0" layer="29"/>
<circle x="10.795" y="-4.445" radius="0.4" width="0" layer="29"/>
<circle x="9.525" y="-4.445" radius="0.4" width="0" layer="29"/>
<circle x="8.255" y="-4.445" radius="0.4" width="0" layer="29"/>
<circle x="-8.255" y="-4.445" radius="0.4" width="0" layer="29"/>
<circle x="-9.525" y="-4.445" radius="0.4" width="0" layer="29"/>
<circle x="-10.795" y="-4.445" radius="0.4" width="0" layer="29"/>
<circle x="-12.065" y="-4.445" radius="0.4" width="0" layer="29"/>
<circle x="12.065" y="-3.175" radius="0.4" width="0" layer="29"/>
<circle x="10.795" y="-3.175" radius="0.4" width="0" layer="29"/>
<circle x="9.525" y="-3.175" radius="0.4" width="0" layer="29"/>
<circle x="8.255" y="-3.175" radius="0.4" width="0" layer="29"/>
<circle x="-8.255" y="-3.175" radius="0.4" width="0" layer="29"/>
<circle x="-9.525" y="-3.175" radius="0.4" width="0" layer="29"/>
<circle x="-10.795" y="-3.175" radius="0.4" width="0" layer="29"/>
<circle x="-12.065" y="-3.175" radius="0.4" width="0" layer="29"/>
<circle x="12.065" y="-1.905" radius="0.4" width="0" layer="29"/>
<circle x="10.795" y="-1.905" radius="0.4" width="0" layer="29"/>
<circle x="9.525" y="-1.905" radius="0.4" width="0" layer="29"/>
<circle x="8.255" y="-1.905" radius="0.4" width="0" layer="29"/>
<circle x="1.905" y="-1.905" radius="0.4" width="0" layer="29"/>
<circle x="0.635" y="-1.905" radius="0.4" width="0" layer="29"/>
<circle x="-0.635" y="-1.905" radius="0.4" width="0" layer="29"/>
<circle x="-1.905" y="-1.905" radius="0.4" width="0" layer="29"/>
<circle x="-8.255" y="-1.905" radius="0.4" width="0" layer="29"/>
<circle x="-9.525" y="-1.905" radius="0.4" width="0" layer="29"/>
<circle x="-10.795" y="-1.905" radius="0.4" width="0" layer="29"/>
<circle x="-12.065" y="-1.905" radius="0.4" width="0" layer="29"/>
<circle x="12.065" y="-0.635" radius="0.4" width="0" layer="29"/>
<circle x="10.795" y="-0.635" radius="0.4" width="0" layer="29"/>
<circle x="9.525" y="-0.635" radius="0.4" width="0" layer="29"/>
<circle x="8.255" y="-0.635" radius="0.4" width="0" layer="29"/>
<circle x="1.905" y="-0.635" radius="0.4" width="0" layer="29"/>
<circle x="0.635" y="-0.635" radius="0.4" width="0" layer="29"/>
<circle x="-0.635" y="-0.635" radius="0.4" width="0" layer="29"/>
<circle x="-1.905" y="-0.635" radius="0.4" width="0" layer="29"/>
<circle x="-8.255" y="-0.635" radius="0.4" width="0" layer="29"/>
<circle x="-9.525" y="-0.635" radius="0.4" width="0" layer="29"/>
<circle x="-10.795" y="-0.635" radius="0.4" width="0" layer="29"/>
<circle x="-12.065" y="-0.635" radius="0.4" width="0" layer="29"/>
<circle x="12.065" y="0.635" radius="0.4" width="0" layer="29"/>
<circle x="10.795" y="0.635" radius="0.4" width="0" layer="29"/>
<circle x="9.525" y="0.635" radius="0.4" width="0" layer="29"/>
<circle x="8.255" y="0.635" radius="0.4" width="0" layer="29"/>
<circle x="1.905" y="0.635" radius="0.4" width="0" layer="29"/>
<circle x="0.635" y="0.635" radius="0.4" width="0" layer="29"/>
<circle x="-0.635" y="0.635" radius="0.4" width="0" layer="29"/>
<circle x="-1.905" y="0.635" radius="0.4" width="0" layer="29"/>
<circle x="-8.255" y="0.635" radius="0.4" width="0" layer="29"/>
<circle x="-9.525" y="0.635" radius="0.4" width="0" layer="29"/>
<circle x="-10.795" y="0.635" radius="0.4" width="0" layer="29"/>
<circle x="-12.065" y="0.635" radius="0.4" width="0" layer="29"/>
<circle x="12.065" y="1.905" radius="0.4" width="0" layer="29"/>
<circle x="10.795" y="1.905" radius="0.4" width="0" layer="29"/>
<circle x="9.525" y="1.905" radius="0.4" width="0" layer="29"/>
<circle x="8.255" y="1.905" radius="0.4" width="0" layer="29"/>
<circle x="1.905" y="1.905" radius="0.4" width="0" layer="29"/>
<circle x="0.635" y="1.905" radius="0.4" width="0" layer="29"/>
<circle x="-0.635" y="1.905" radius="0.4" width="0" layer="29"/>
<circle x="-1.905" y="1.905" radius="0.4" width="0" layer="29"/>
<circle x="-8.255" y="1.905" radius="0.4" width="0" layer="29"/>
<circle x="-9.525" y="1.905" radius="0.4" width="0" layer="29"/>
<circle x="-10.795" y="1.905" radius="0.4" width="0" layer="29"/>
<circle x="-12.065" y="1.905" radius="0.4" width="0" layer="29"/>
<circle x="12.065" y="3.175" radius="0.4" width="0" layer="29"/>
<circle x="10.795" y="3.175" radius="0.4" width="0" layer="29"/>
<circle x="9.525" y="3.175" radius="0.4" width="0" layer="29"/>
<circle x="8.255" y="3.175" radius="0.4" width="0" layer="29"/>
<circle x="-8.255" y="3.175" radius="0.4" width="0" layer="29"/>
<circle x="-9.525" y="3.175" radius="0.4" width="0" layer="29"/>
<circle x="-10.795" y="3.175" radius="0.4" width="0" layer="29"/>
<circle x="-12.065" y="3.175" radius="0.4" width="0" layer="29"/>
<circle x="12.065" y="4.445" radius="0.4" width="0" layer="29"/>
<circle x="10.795" y="4.445" radius="0.4" width="0" layer="29"/>
<circle x="9.525" y="4.445" radius="0.4" width="0" layer="29"/>
<circle x="8.255" y="4.445" radius="0.4" width="0" layer="29"/>
<circle x="-8.255" y="4.445" radius="0.4" width="0" layer="29"/>
<circle x="-9.525" y="4.445" radius="0.4" width="0" layer="29"/>
<circle x="-10.795" y="4.445" radius="0.4" width="0" layer="29"/>
<circle x="-12.065" y="4.445" radius="0.4" width="0" layer="29"/>
<circle x="12.065" y="5.715" radius="0.4" width="0" layer="29"/>
<circle x="10.795" y="5.715" radius="0.4" width="0" layer="29"/>
<circle x="9.525" y="5.715" radius="0.4" width="0" layer="29"/>
<circle x="8.255" y="5.715" radius="0.4" width="0" layer="29"/>
<circle x="-8.255" y="5.715" radius="0.4" width="0" layer="29"/>
<circle x="-9.525" y="5.715" radius="0.4" width="0" layer="29"/>
<circle x="-10.795" y="5.715" radius="0.4" width="0" layer="29"/>
<circle x="-12.065" y="5.715" radius="0.4" width="0" layer="29"/>
<circle x="12.065" y="6.985" radius="0.4" width="0" layer="29"/>
<circle x="10.795" y="6.985" radius="0.4" width="0" layer="29"/>
<circle x="9.525" y="6.985" radius="0.4" width="0" layer="29"/>
<circle x="8.255" y="6.985" radius="0.4" width="0" layer="29"/>
<circle x="-8.255" y="6.985" radius="0.4" width="0" layer="29"/>
<circle x="-9.525" y="6.985" radius="0.4" width="0" layer="29"/>
<circle x="-10.795" y="6.985" radius="0.4" width="0" layer="29"/>
<circle x="-12.065" y="6.985" radius="0.4" width="0" layer="29"/>
<circle x="12.065" y="8.255" radius="0.4" width="0" layer="29"/>
<circle x="10.795" y="8.255" radius="0.4" width="0" layer="29"/>
<circle x="9.525" y="8.255" radius="0.4" width="0" layer="29"/>
<circle x="8.255" y="8.255" radius="0.4" width="0" layer="29"/>
<circle x="6.985" y="8.255" radius="0.4" width="0" layer="29"/>
<circle x="5.715" y="8.255" radius="0.4" width="0" layer="29"/>
<circle x="4.445" y="8.255" radius="0.4" width="0" layer="29"/>
<circle x="3.175" y="8.255" radius="0.4" width="0" layer="29"/>
<circle x="1.905" y="8.255" radius="0.4" width="0" layer="29"/>
<circle x="0.635" y="8.255" radius="0.4" width="0" layer="29"/>
<circle x="-0.635" y="8.255" radius="0.4" width="0" layer="29"/>
<circle x="-1.905" y="8.255" radius="0.4" width="0" layer="29"/>
<circle x="-3.175" y="8.255" radius="0.4" width="0" layer="29"/>
<circle x="-4.445" y="8.255" radius="0.4" width="0" layer="29"/>
<circle x="-5.715" y="8.255" radius="0.4" width="0" layer="29"/>
<circle x="-6.985" y="8.255" radius="0.4" width="0" layer="29"/>
<circle x="-8.255" y="8.255" radius="0.4" width="0" layer="29"/>
<circle x="-9.525" y="8.255" radius="0.4" width="0" layer="29"/>
<circle x="-10.795" y="8.255" radius="0.4" width="0" layer="29"/>
<circle x="-12.065" y="8.255" radius="0.4" width="0" layer="29"/>
<circle x="12.065" y="9.525" radius="0.4" width="0" layer="29"/>
<circle x="10.795" y="9.525" radius="0.4" width="0" layer="29"/>
<circle x="9.525" y="9.525" radius="0.4" width="0" layer="29"/>
<circle x="8.255" y="9.525" radius="0.4" width="0" layer="29"/>
<circle x="6.985" y="9.525" radius="0.4" width="0" layer="29"/>
<circle x="5.715" y="9.525" radius="0.4" width="0" layer="29"/>
<circle x="4.445" y="9.525" radius="0.4" width="0" layer="29"/>
<circle x="3.175" y="9.525" radius="0.4" width="0" layer="29"/>
<circle x="1.905" y="9.525" radius="0.4" width="0" layer="29"/>
<circle x="0.635" y="9.525" radius="0.4" width="0" layer="29"/>
<circle x="-0.635" y="9.525" radius="0.4" width="0" layer="29"/>
<circle x="-1.905" y="9.525" radius="0.4" width="0" layer="29"/>
<circle x="-3.175" y="9.525" radius="0.4" width="0" layer="29"/>
<circle x="-4.445" y="9.525" radius="0.4" width="0" layer="29"/>
<circle x="-5.715" y="9.525" radius="0.4" width="0" layer="29"/>
<circle x="-6.985" y="9.525" radius="0.4" width="0" layer="29"/>
<circle x="-8.255" y="9.525" radius="0.4" width="0" layer="29"/>
<circle x="-9.525" y="9.525" radius="0.4" width="0" layer="29"/>
<circle x="-10.795" y="9.525" radius="0.4" width="0" layer="29"/>
<circle x="-12.065" y="9.525" radius="0.4" width="0" layer="29"/>
<circle x="12.065" y="10.795" radius="0.4" width="0" layer="29"/>
<circle x="10.795" y="10.795" radius="0.4" width="0" layer="29"/>
<circle x="9.525" y="10.795" radius="0.4" width="0" layer="29"/>
<circle x="8.255" y="10.795" radius="0.4" width="0" layer="29"/>
<circle x="6.985" y="10.795" radius="0.4" width="0" layer="29"/>
<circle x="5.715" y="10.795" radius="0.4" width="0" layer="29"/>
<circle x="4.445" y="10.795" radius="0.4" width="0" layer="29"/>
<circle x="3.175" y="10.795" radius="0.4" width="0" layer="29"/>
<circle x="1.905" y="10.795" radius="0.4" width="0" layer="29"/>
<circle x="0.635" y="10.795" radius="0.4" width="0" layer="29"/>
<circle x="-0.635" y="10.795" radius="0.4" width="0" layer="29"/>
<circle x="-1.905" y="10.795" radius="0.4" width="0" layer="29"/>
<circle x="-3.175" y="10.795" radius="0.4" width="0" layer="29"/>
<circle x="-4.445" y="10.795" radius="0.4" width="0" layer="29"/>
<circle x="-5.715" y="10.795" radius="0.4" width="0" layer="29"/>
<circle x="-6.985" y="10.795" radius="0.4" width="0" layer="29"/>
<circle x="-8.255" y="10.795" radius="0.4" width="0" layer="29"/>
<circle x="-9.525" y="10.795" radius="0.4" width="0" layer="29"/>
<circle x="-10.795" y="10.795" radius="0.4" width="0" layer="29"/>
<circle x="-12.065" y="10.795" radius="0.4" width="0" layer="29"/>
<circle x="12.065" y="12.065" radius="0.4" width="0" layer="29"/>
<circle x="10.795" y="12.065" radius="0.4" width="0" layer="29"/>
<circle x="9.525" y="12.065" radius="0.4" width="0" layer="29"/>
<circle x="8.255" y="12.065" radius="0.4" width="0" layer="29"/>
<circle x="6.985" y="12.065" radius="0.4" width="0" layer="29"/>
<circle x="5.715" y="12.065" radius="0.4" width="0" layer="29"/>
<circle x="4.445" y="12.065" radius="0.4" width="0" layer="29"/>
<circle x="3.175" y="12.065" radius="0.4" width="0" layer="29"/>
<circle x="1.905" y="12.065" radius="0.4" width="0" layer="29"/>
<circle x="0.635" y="12.065" radius="0.4" width="0" layer="29"/>
<circle x="-0.635" y="12.065" radius="0.4" width="0" layer="29"/>
<circle x="-1.905" y="12.065" radius="0.4" width="0" layer="29"/>
<circle x="-3.175" y="12.065" radius="0.4" width="0" layer="29"/>
<circle x="-4.445" y="12.065" radius="0.4" width="0" layer="29"/>
<circle x="-5.715" y="12.065" radius="0.4" width="0" layer="29"/>
<circle x="-6.985" y="12.065" radius="0.4" width="0" layer="29"/>
<circle x="-8.255" y="12.065" radius="0.4" width="0" layer="29"/>
<circle x="-9.525" y="12.065" radius="0.4" width="0" layer="29"/>
<circle x="-10.795" y="12.065" radius="0.4" width="0" layer="29"/>
<circle x="-12.065" y="12.065" radius="0.4" width="0" layer="29"/>
<smd name="Y20" x="12.065" y="-12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="Y19" x="10.795" y="-12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="Y18" x="9.525" y="-12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="Y17" x="8.255" y="-12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="Y16" x="6.985" y="-12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="Y15" x="5.715" y="-12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="Y14" x="4.445" y="-12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="Y13" x="3.175" y="-12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="Y12" x="1.905" y="-12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="Y11" x="0.635" y="-12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="Y10" x="-0.635" y="-12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="Y9" x="-1.905" y="-12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="Y8" x="-3.175" y="-12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="Y7" x="-4.445" y="-12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="Y6" x="-5.715" y="-12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="Y5" x="-6.985" y="-12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="Y4" x="-8.255" y="-12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="Y3" x="-9.525" y="-12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="Y2" x="-10.795" y="-12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="Y1" x="-12.065" y="-12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="W20" x="12.065" y="-10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="W19" x="10.795" y="-10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="W18" x="9.525" y="-10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="W17" x="8.255" y="-10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="W16" x="6.985" y="-10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="W15" x="5.715" y="-10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="W14" x="4.445" y="-10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="W13" x="3.175" y="-10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="W12" x="1.905" y="-10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="W11" x="0.635" y="-10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="W10" x="-0.635" y="-10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="W9" x="-1.905" y="-10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="W8" x="-3.175" y="-10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="W7" x="-4.445" y="-10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="W6" x="-5.715" y="-10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="W5" x="-6.985" y="-10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="W4" x="-8.255" y="-10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="W3" x="-9.525" y="-10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="W2" x="-10.795" y="-10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="W1" x="-12.065" y="-10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="V20" x="12.065" y="-9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="V19" x="10.795" y="-9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="V18" x="9.525" y="-9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="V17" x="8.255" y="-9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="V16" x="6.985" y="-9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="V15" x="5.715" y="-9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="V14" x="4.445" y="-9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="V13" x="3.175" y="-9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="V12" x="1.905" y="-9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="V11" x="0.635" y="-9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="V10" x="-0.635" y="-9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="V9" x="-1.905" y="-9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="V8" x="-3.175" y="-9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="V7" x="-4.445" y="-9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="V6" x="-5.715" y="-9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="V5" x="-6.985" y="-9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="V4" x="-8.255" y="-9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="V3" x="-9.525" y="-9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="V2" x="-10.795" y="-9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="V1" x="-12.065" y="-9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="U20" x="12.065" y="-8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="U19" x="10.795" y="-8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="U18" x="9.525" y="-8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="U17" x="8.255" y="-8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="U16" x="6.985" y="-8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="U15" x="5.715" y="-8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="U14" x="4.445" y="-8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="U13" x="3.175" y="-8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="U12" x="1.905" y="-8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="U11" x="0.635" y="-8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="U10" x="-0.635" y="-8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="U9" x="-1.905" y="-8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="U8" x="-3.175" y="-8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="U7" x="-4.445" y="-8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="U6" x="-5.715" y="-8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="U5" x="-6.985" y="-8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="U4" x="-8.255" y="-8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="U3" x="-9.525" y="-8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="U2" x="-10.795" y="-8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="U1" x="-12.065" y="-8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="T20" x="12.065" y="-6.985" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="T19" x="10.795" y="-6.985" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="T18" x="9.525" y="-6.985" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="T17" x="8.255" y="-6.985" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="T4" x="-8.255" y="-6.985" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="T3" x="-9.525" y="-6.985" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="T2" x="-10.795" y="-6.985" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="T1" x="-12.065" y="-6.985" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="R20" x="12.065" y="-5.715" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="R19" x="10.795" y="-5.715" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="R18" x="9.525" y="-5.715" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="R17" x="8.255" y="-5.715" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="R4" x="-8.255" y="-5.715" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="R3" x="-9.525" y="-5.715" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="R2" x="-10.795" y="-5.715" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="R1" x="-12.065" y="-5.715" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="P20" x="12.065" y="-4.445" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="P19" x="10.795" y="-4.445" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="P18" x="9.525" y="-4.445" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="P17" x="8.255" y="-4.445" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="P4" x="-8.255" y="-4.445" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="P3" x="-9.525" y="-4.445" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="P2" x="-10.795" y="-4.445" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="P1" x="-12.065" y="-4.445" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="N20" x="12.065" y="-3.175" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="N19" x="10.795" y="-3.175" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="N18" x="9.525" y="-3.175" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="N17" x="8.255" y="-3.175" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="N4" x="-8.255" y="-3.175" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="N3" x="-9.525" y="-3.175" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="N2" x="-10.795" y="-3.175" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="N1" x="-12.065" y="-3.175" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="M20" x="12.065" y="-1.905" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="M19" x="10.795" y="-1.905" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="M18" x="9.525" y="-1.905" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="M17" x="8.255" y="-1.905" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="M12" x="1.905" y="-1.905" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="M11" x="0.635" y="-1.905" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="M10" x="-0.635" y="-1.905" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="M9" x="-1.905" y="-1.905" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="M4" x="-8.255" y="-1.905" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="M3" x="-9.525" y="-1.905" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="M2" x="-10.795" y="-1.905" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="M1" x="-12.065" y="-1.905" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="L20" x="12.065" y="-0.635" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="L19" x="10.795" y="-0.635" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="L18" x="9.525" y="-0.635" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="L17" x="8.255" y="-0.635" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="L12" x="1.905" y="-0.635" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="L11" x="0.635" y="-0.635" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="L10" x="-0.635" y="-0.635" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="L9" x="-1.905" y="-0.635" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="L4" x="-8.255" y="-0.635" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="L3" x="-9.525" y="-0.635" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="L2" x="-10.795" y="-0.635" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="L1" x="-12.065" y="-0.635" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="K20" x="12.065" y="0.635" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="K19" x="10.795" y="0.635" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="K18" x="9.525" y="0.635" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="K17" x="8.255" y="0.635" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="K12" x="1.905" y="0.635" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="K11" x="0.635" y="0.635" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="K10" x="-0.635" y="0.635" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="K9" x="-1.905" y="0.635" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="K4" x="-8.255" y="0.635" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="K3" x="-9.525" y="0.635" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="K2" x="-10.795" y="0.635" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="K1" x="-12.065" y="0.635" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="J20" x="12.065" y="1.905" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="J19" x="10.795" y="1.905" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="J18" x="9.525" y="1.905" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="J17" x="8.255" y="1.905" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="J12" x="1.905" y="1.905" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="J11" x="0.635" y="1.905" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="J10" x="-0.635" y="1.905" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="J9" x="-1.905" y="1.905" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="J4" x="-8.255" y="1.905" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="J3" x="-9.525" y="1.905" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="J2" x="-10.795" y="1.905" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="J1" x="-12.065" y="1.905" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="H20" x="12.065" y="3.175" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="H19" x="10.795" y="3.175" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="H18" x="9.525" y="3.175" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="H17" x="8.255" y="3.175" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="H4" x="-8.255" y="3.175" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="H3" x="-9.525" y="3.175" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="H2" x="-10.795" y="3.175" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="H1" x="-12.065" y="3.175" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="G20" x="12.065" y="4.445" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="G19" x="10.795" y="4.445" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="G18" x="9.525" y="4.445" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="G17" x="8.255" y="4.445" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="G4" x="-8.255" y="4.445" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="G3" x="-9.525" y="4.445" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="G2" x="-10.795" y="4.445" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="G1" x="-12.065" y="4.445" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="F20" x="12.065" y="5.715" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="F19" x="10.795" y="5.715" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="F18" x="9.525" y="5.715" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="F17" x="8.255" y="5.715" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="F4" x="-8.255" y="5.715" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="F3" x="-9.525" y="5.715" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="F2" x="-10.795" y="5.715" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="F1" x="-12.065" y="5.715" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="E20" x="12.065" y="6.985" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="E19" x="10.795" y="6.985" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="E18" x="9.525" y="6.985" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="E17" x="8.255" y="6.985" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="E4" x="-8.255" y="6.985" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="E3" x="-9.525" y="6.985" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="E2" x="-10.795" y="6.985" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="E1" x="-12.065" y="6.985" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="D20" x="12.065" y="8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="D19" x="10.795" y="8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="D18" x="9.525" y="8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="D17" x="8.255" y="8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="D16" x="6.985" y="8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="D15" x="5.715" y="8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="D14" x="4.445" y="8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="D13" x="3.175" y="8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="D12" x="1.905" y="8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="D11" x="0.635" y="8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="D10" x="-0.635" y="8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="D9" x="-1.905" y="8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="D8" x="-3.175" y="8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="D7" x="-4.445" y="8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="D6" x="-5.715" y="8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="D5" x="-6.985" y="8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="D4" x="-8.255" y="8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="D3" x="-9.525" y="8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="D2" x="-10.795" y="8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="D1" x="-12.065" y="8.255" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="C20" x="12.065" y="9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="C19" x="10.795" y="9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="C18" x="9.525" y="9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="C17" x="8.255" y="9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="C16" x="6.985" y="9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="C15" x="5.715" y="9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="C14" x="4.445" y="9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="C13" x="3.175" y="9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="C12" x="1.905" y="9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="C11" x="0.635" y="9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="C10" x="-0.635" y="9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="C9" x="-1.905" y="9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="C8" x="-3.175" y="9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="C7" x="-4.445" y="9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="C6" x="-5.715" y="9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="C5" x="-6.985" y="9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="C4" x="-8.255" y="9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="C3" x="-9.525" y="9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="C2" x="-10.795" y="9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="C1" x="-12.065" y="9.525" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="B20" x="12.065" y="10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="B19" x="10.795" y="10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="B18" x="9.525" y="10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="B17" x="8.255" y="10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="B16" x="6.985" y="10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="B15" x="5.715" y="10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="B14" x="4.445" y="10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="B13" x="3.175" y="10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="B12" x="1.905" y="10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="B11" x="0.635" y="10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="B10" x="-0.635" y="10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="B9" x="-1.905" y="10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="B8" x="-3.175" y="10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="B7" x="-4.445" y="10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="B6" x="-5.715" y="10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="B5" x="-6.985" y="10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="B4" x="-8.255" y="10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="B3" x="-9.525" y="10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="B2" x="-10.795" y="10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="B1" x="-12.065" y="10.795" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="A20" x="12.065" y="12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="A19" x="10.795" y="12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="A18" x="9.525" y="12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="A17" x="8.255" y="12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="A16" x="6.985" y="12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="A15" x="5.715" y="12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="A14" x="4.445" y="12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="A13" x="3.175" y="12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="A12" x="1.905" y="12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="A11" x="0.635" y="12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="A10" x="-0.635" y="12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="A9" x="-1.905" y="12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="A8" x="-3.175" y="12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="A7" x="-4.445" y="12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="A6" x="-5.715" y="12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="A5" x="-6.985" y="12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="A4" x="-8.255" y="12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="A3" x="-9.525" y="12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="A2" x="-10.795" y="12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<smd name="A1" x="-12.065" y="12.065" dx="0.8" dy="0.8" layer="1" roundness="100" stop="no" cream="no"/>
<text x="-5.08" y="3.81" size="1.27" layer="25">&gt;NAME</text>
<text x="-5.08" y="-5.715" size="1.27" layer="27">&gt;VALUE</text>
</package>
</packages>
<symbols>
<symbol name="XCV200ES_BG256" library_version="1">
<text x="-55.88" y="86.36" size="1.778" layer="95">&gt;NAME</text>
<text x="-55.88" y="83.82" size="1.778" layer="96">&gt;VALUE</text>
<pin name="CCLK" x="-55.88" y="81.28" length="middle"/>
<pin name="DONE" x="-55.88" y="78.74" length="middle"/>
<pin name="DXN" x="-55.88" y="76.2" length="middle" direction="pas"/>
<pin name="DXP" x="-55.88" y="73.66" length="middle" direction="pas"/>
<pin name="GCLKPAD0" x="-55.88" y="71.12" length="middle" direction="in"/>
<pin name="GCLKPAD1" x="-55.88" y="68.58" length="middle" direction="in"/>
<pin name="GCLKPAD2" x="-55.88" y="66.04" length="middle" direction="in"/>
<pin name="GCLKPAD3" x="-55.88" y="63.5" length="middle" direction="in"/>
<pin name="GND@1" x="-55.88" y="60.96" length="middle" direction="pwr"/>
<pin name="GND@2" x="-55.88" y="58.42" length="middle" direction="pwr"/>
<pin name="GND@3" x="-55.88" y="55.88" length="middle" direction="pwr"/>
<pin name="GND@4" x="-55.88" y="53.34" length="middle" direction="pwr"/>
<pin name="GND@5" x="-55.88" y="50.8" length="middle" direction="pwr"/>
<pin name="GND@6" x="-55.88" y="48.26" length="middle" direction="pwr"/>
<pin name="GND@7" x="-55.88" y="45.72" length="middle" direction="pwr"/>
<pin name="GND@8" x="-55.88" y="43.18" length="middle" direction="pwr"/>
<pin name="GND@9" x="-55.88" y="40.64" length="middle" direction="pwr"/>
<pin name="GND@10" x="-55.88" y="38.1" length="middle" direction="pwr"/>
<pin name="GND@11" x="-55.88" y="35.56" length="middle" direction="pwr"/>
<pin name="GND@12" x="-55.88" y="33.02" length="middle" direction="pwr"/>
<pin name="GND@13" x="-55.88" y="30.48" length="middle" direction="pwr"/>
<pin name="GND@14" x="-55.88" y="27.94" length="middle" direction="pwr"/>
<pin name="GND@15" x="-55.88" y="25.4" length="middle" direction="pwr"/>
<pin name="GND@16" x="-55.88" y="22.86" length="middle" direction="pwr"/>
<pin name="GND@17" x="-55.88" y="20.32" length="middle" direction="pwr"/>
<pin name="GND@18" x="-55.88" y="17.78" length="middle" direction="pwr"/>
<pin name="GND@19" x="-55.88" y="15.24" length="middle" direction="pwr"/>
<pin name="GND@20" x="-55.88" y="12.7" length="middle" direction="pwr"/>
<pin name="GND@21" x="-55.88" y="10.16" length="middle" direction="pwr"/>
<pin name="GND@22" x="-55.88" y="7.62" length="middle" direction="pwr"/>
<pin name="GND@23" x="-55.88" y="5.08" length="middle" direction="pwr"/>
<pin name="GND@24" x="-55.88" y="2.54" length="middle" direction="pwr"/>
<pin name="GND@25" x="-55.88" y="0" length="middle" direction="pwr"/>
<pin name="GND@26" x="-55.88" y="-2.54" length="middle" direction="pwr"/>
<pin name="GND@27" x="-55.88" y="-5.08" length="middle" direction="pwr"/>
<pin name="GND@28" x="-55.88" y="-7.62" length="middle" direction="pwr"/>
<pin name="GND@29" x="-55.88" y="-10.16" length="middle" direction="pwr"/>
<pin name="GND@30" x="-55.88" y="-12.7" length="middle" direction="pwr"/>
<pin name="GND@31" x="-55.88" y="-15.24" length="middle" direction="pwr"/>
<pin name="GND@32" x="-55.88" y="-17.78" length="middle" direction="pwr"/>
<pin name="GND@33" x="-55.88" y="-20.32" length="middle" direction="pwr"/>
<pin name="GND@34" x="-55.88" y="-22.86" length="middle" direction="pwr"/>
<pin name="GND@35" x="-55.88" y="-25.4" length="middle" direction="pwr"/>
<pin name="GND@36" x="-55.88" y="-27.94" length="middle" direction="pwr"/>
<pin name="GND@37" x="-55.88" y="-30.48" length="middle" direction="pwr"/>
<pin name="GND@38" x="-55.88" y="-33.02" length="middle" direction="pwr"/>
<pin name="GND@39" x="-55.88" y="-35.56" length="middle" direction="pwr"/>
<pin name="GND@40" x="-55.88" y="-38.1" length="middle" direction="pwr"/>
<pin name="GND@41" x="-55.88" y="-40.64" length="middle" direction="pwr"/>
<pin name="GND@42" x="-55.88" y="-43.18" length="middle" direction="pwr"/>
<pin name="GND@43" x="-55.88" y="-45.72" length="middle" direction="pwr"/>
<pin name="GND@44" x="-55.88" y="-48.26" length="middle" direction="pwr"/>
<pin name="GND@45" x="-55.88" y="-50.8" length="middle" direction="pwr"/>
<pin name="GND@46" x="-55.88" y="-53.34" length="middle" direction="pwr"/>
<pin name="GND@47" x="-55.88" y="-55.88" length="middle" direction="pwr"/>
<pin name="GND@48" x="-55.88" y="-58.42" length="middle" direction="pwr"/>
<pin name="INIT" x="-55.88" y="-60.96" length="middle"/>
<pin name="M0" x="-55.88" y="-63.5" length="middle" direction="in"/>
<pin name="M1" x="-55.88" y="-66.04" length="middle" direction="in"/>
<pin name="M2" x="-55.88" y="-68.58" length="middle" direction="in"/>
<pin name="PAD2" x="-55.88" y="-71.12" length="middle"/>
<pin name="PAD6" x="-55.88" y="-73.66" length="middle"/>
<pin name="PAD7" x="-30.48" y="81.28" length="middle"/>
<pin name="PAD11" x="-30.48" y="78.74" length="middle"/>
<pin name="PAD12" x="-30.48" y="76.2" length="middle"/>
<pin name="PAD13" x="-30.48" y="73.66" length="middle"/>
<pin name="PAD14" x="-30.48" y="71.12" length="middle"/>
<pin name="PAD17" x="-30.48" y="68.58" length="middle"/>
<pin name="PAD18" x="-30.48" y="66.04" length="middle"/>
<pin name="PAD21" x="-30.48" y="63.5" length="middle"/>
<pin name="PAD22" x="-30.48" y="60.96" length="middle"/>
<pin name="PAD23" x="-30.48" y="58.42" length="middle"/>
<pin name="PAD24" x="-30.48" y="55.88" length="middle"/>
<pin name="PAD27" x="-30.48" y="53.34" length="middle"/>
<pin name="PAD28" x="-30.48" y="50.8" length="middle"/>
<pin name="PAD31" x="-30.48" y="48.26" length="middle"/>
<pin name="PAD32" x="-30.48" y="45.72" length="middle"/>
<pin name="PAD33" x="-30.48" y="43.18" length="middle"/>
<pin name="PAD34" x="-30.48" y="40.64" length="middle"/>
<pin name="PAD37" x="-30.48" y="38.1" length="middle"/>
<pin name="PAD38" x="-30.48" y="35.56" length="middle"/>
<pin name="PAD44" x="-30.48" y="33.02" length="middle"/>
<pin name="PAD47" x="-30.48" y="30.48" length="middle"/>
<pin name="PAD48" x="-30.48" y="27.94" length="middle"/>
<pin name="PAD51" x="-30.48" y="25.4" length="middle"/>
<pin name="PAD52" x="-30.48" y="22.86" length="middle"/>
<pin name="PAD53" x="-30.48" y="20.32" length="middle"/>
<pin name="PAD54" x="-30.48" y="17.78" length="middle"/>
<pin name="PAD57" x="-30.48" y="15.24" length="middle"/>
<pin name="PAD58" x="-30.48" y="12.7" length="middle"/>
<pin name="PAD61" x="-30.48" y="10.16" length="middle"/>
<pin name="PAD62" x="-30.48" y="7.62" length="middle"/>
<pin name="PAD63" x="-30.48" y="5.08" length="middle"/>
<pin name="PAD64" x="-30.48" y="2.54" length="middle"/>
<pin name="PAD67" x="-30.48" y="0" length="middle"/>
<pin name="PAD68" x="-30.48" y="-2.54" length="middle"/>
<pin name="PAD71" x="-30.48" y="-5.08" length="middle"/>
<pin name="PAD72" x="-30.48" y="-7.62" length="middle"/>
<pin name="PAD73" x="-30.48" y="-10.16" length="middle"/>
<pin name="PAD74" x="-30.48" y="-12.7" length="middle"/>
<pin name="PAD78" x="-30.48" y="-15.24" length="middle"/>
<pin name="PAD79" x="-30.48" y="-17.78" length="middle"/>
<pin name="PAD83" x="-30.48" y="-20.32" length="middle"/>
<pin name="PAD84" x="-30.48" y="-22.86" length="middle"/>
<pin name="PAD85" x="-30.48" y="-25.4" length="middle"/>
<pin name="PAD86" x="-30.48" y="-27.94" length="middle"/>
<pin name="PAD90" x="-30.48" y="-30.48" length="middle"/>
<pin name="PAD91" x="-30.48" y="-33.02" length="middle"/>
<pin name="PAD95" x="-30.48" y="-35.56" length="middle"/>
<pin name="PAD96" x="-30.48" y="-38.1" length="middle"/>
<pin name="PAD97" x="-30.48" y="-40.64" length="middle"/>
<pin name="PAD98" x="-30.48" y="-43.18" length="middle"/>
<pin name="PAD101" x="-30.48" y="-45.72" length="middle"/>
<pin name="PAD102" x="-30.48" y="-48.26" length="middle"/>
<pin name="PAD105" x="-30.48" y="-50.8" length="middle"/>
<pin name="PAD106" x="-30.48" y="-53.34" length="middle"/>
<pin name="PAD107" x="-30.48" y="-55.88" length="middle"/>
<pin name="PAD108" x="-30.48" y="-58.42" length="middle"/>
<pin name="PAD111" x="-30.48" y="-60.96" length="middle"/>
<pin name="PAD112" x="-30.48" y="-63.5" length="middle"/>
<pin name="PAD115" x="-30.48" y="-66.04" length="middle"/>
<pin name="PAD116" x="-30.48" y="-68.58" length="middle"/>
<pin name="PAD117" x="-30.48" y="-71.12" length="middle"/>
<pin name="PAD118" x="-30.48" y="-73.66" length="middle"/>
<pin name="PAD121" x="-5.08" y="81.28" length="middle"/>
<pin name="PAD122" x="-5.08" y="78.74" length="middle"/>
<pin name="PAD125" x="-5.08" y="76.2" length="middle"/>
<pin name="PAD126" x="-5.08" y="73.66" length="middle"/>
<pin name="PAD127" x="-5.08" y="71.12" length="middle"/>
<pin name="PAD131" x="-5.08" y="68.58" length="middle"/>
<pin name="PAD132" x="-5.08" y="66.04" length="middle"/>
<pin name="PAD135" x="-5.08" y="63.5" length="middle"/>
<pin name="PAD136" x="-5.08" y="60.96" length="middle"/>
<pin name="PAD137" x="-5.08" y="58.42" length="middle"/>
<pin name="PAD138" x="-5.08" y="55.88" length="middle"/>
<pin name="PAD141" x="-5.08" y="53.34" length="middle"/>
<pin name="PAD142" x="-5.08" y="50.8" length="middle"/>
<pin name="PAD145" x="-5.08" y="48.26" length="middle"/>
<pin name="PAD146" x="-5.08" y="45.72" length="middle"/>
<pin name="PAD147" x="-5.08" y="43.18" length="middle"/>
<pin name="PAD148" x="-5.08" y="40.64" length="middle"/>
<pin name="PAD151" x="-5.08" y="38.1" length="middle"/>
<pin name="PAD152" x="-5.08" y="35.56" length="middle"/>
<pin name="PAD155" x="-5.08" y="33.02" length="middle"/>
<pin name="PAD156" x="-5.08" y="30.48" length="middle"/>
<pin name="PAD157" x="-5.08" y="27.94" length="middle"/>
<pin name="PAD158" x="-5.08" y="25.4" length="middle"/>
<pin name="PAD162" x="-5.08" y="22.86" length="middle"/>
<pin name="PAD163" x="-5.08" y="20.32" length="middle"/>
<pin name="PAD167" x="-5.08" y="17.78" length="middle"/>
<pin name="PAD169" x="-5.08" y="15.24" length="middle"/>
<pin name="PAD170" x="-5.08" y="12.7" length="middle"/>
<pin name="PAD174" x="-5.08" y="10.16" length="middle"/>
<pin name="PAD175" x="-5.08" y="7.62" length="middle"/>
<pin name="PAD179" x="-5.08" y="5.08" length="middle"/>
<pin name="PAD180" x="-5.08" y="2.54" length="middle"/>
<pin name="PAD181" x="-5.08" y="0" length="middle"/>
<pin name="PAD182" x="-5.08" y="-2.54" length="middle"/>
<pin name="PAD185" x="-5.08" y="-5.08" length="middle"/>
<pin name="PAD186" x="-5.08" y="-7.62" length="middle"/>
<pin name="PAD189" x="-5.08" y="-10.16" length="middle"/>
<pin name="PAD190" x="-5.08" y="-12.7" length="middle"/>
<pin name="PAD191" x="-5.08" y="-15.24" length="middle"/>
<pin name="PAD192" x="-5.08" y="-17.78" length="middle"/>
<pin name="PAD195" x="-5.08" y="-20.32" length="middle"/>
<pin name="PAD196" x="-5.08" y="-22.86" length="middle"/>
<pin name="PAD199" x="-5.08" y="-25.4" length="middle"/>
<pin name="PAD200" x="-5.08" y="-27.94" length="middle"/>
<pin name="PAD201" x="-5.08" y="-30.48" length="middle"/>
<pin name="PAD202" x="-5.08" y="-33.02" length="middle"/>
<pin name="PAD205" x="-5.08" y="-35.56" length="middle"/>
<pin name="PAD206" x="-5.08" y="-38.1" length="middle"/>
<pin name="PAD209" x="-5.08" y="-40.64" length="middle"/>
<pin name="PAD215" x="-5.08" y="-43.18" length="middle"/>
<pin name="PAD216" x="-5.08" y="-45.72" length="middle"/>
<pin name="PAD219" x="-5.08" y="-48.26" length="middle"/>
<pin name="PAD220" x="-5.08" y="-50.8" length="middle"/>
<pin name="PAD221" x="-5.08" y="-53.34" length="middle"/>
<pin name="PAD222" x="-5.08" y="-55.88" length="middle"/>
<pin name="PAD225" x="-5.08" y="-58.42" length="middle"/>
<pin name="PAD226" x="-5.08" y="-60.96" length="middle"/>
<pin name="PAD229" x="-5.08" y="-63.5" length="middle"/>
<pin name="PAD230" x="-5.08" y="-66.04" length="middle"/>
<pin name="PAD231" x="-5.08" y="-68.58" length="middle"/>
<pin name="PAD232" x="-5.08" y="-71.12" length="middle"/>
<pin name="PAD235" x="-5.08" y="-73.66" length="middle"/>
<pin name="PAD236" x="20.32" y="81.28" length="middle"/>
<pin name="PAD239" x="20.32" y="78.74" length="middle"/>
<pin name="PAD240" x="20.32" y="76.2" length="middle"/>
<pin name="PAD241" x="20.32" y="73.66" length="middle"/>
<pin name="PAD242" x="20.32" y="71.12" length="middle"/>
<pin name="PAD246" x="20.32" y="68.58" length="middle"/>
<pin name="PAD247" x="20.32" y="66.04" length="middle"/>
<pin name="PAD253" x="20.32" y="63.5" length="middle"/>
<pin name="PAD254" x="20.32" y="60.96" length="middle"/>
<pin name="PAD258" x="20.32" y="58.42" length="middle"/>
<pin name="PAD259" x="20.32" y="55.88" length="middle"/>
<pin name="PAD263" x="20.32" y="53.34" length="middle"/>
<pin name="PAD264" x="20.32" y="50.8" length="middle"/>
<pin name="PAD265" x="20.32" y="48.26" length="middle"/>
<pin name="PAD266" x="20.32" y="45.72" length="middle"/>
<pin name="PAD269" x="20.32" y="43.18" length="middle"/>
<pin name="PAD270" x="20.32" y="40.64" length="middle"/>
<pin name="PAD273" x="20.32" y="38.1" length="middle"/>
<pin name="PAD274" x="20.32" y="35.56" length="middle"/>
<pin name="PAD275" x="20.32" y="33.02" length="middle"/>
<pin name="PAD276" x="20.32" y="30.48" length="middle"/>
<pin name="PAD279" x="20.32" y="27.94" length="middle"/>
<pin name="PAD280" x="20.32" y="25.4" length="middle"/>
<pin name="PAD283" x="20.32" y="22.86" length="middle"/>
<pin name="PAD284" x="20.32" y="20.32" length="middle"/>
<pin name="PAD285" x="20.32" y="17.78" length="middle"/>
<pin name="PAD286" x="20.32" y="15.24" length="middle"/>
<pin name="PAD289" x="20.32" y="12.7" length="middle"/>
<pin name="PAD290" x="20.32" y="10.16" length="middle"/>
<pin name="PAD294" x="20.32" y="7.62" length="middle"/>
<pin name="PAD295" x="20.32" y="5.08" length="middle"/>
<pin name="PAD296" x="20.32" y="2.54" length="middle"/>
<pin name="PAD299" x="20.32" y="0" length="middle"/>
<pin name="PAD300" x="20.32" y="-2.54" length="middle"/>
<pin name="PAD303" x="20.32" y="-5.08" length="middle"/>
<pin name="PAD304" x="20.32" y="-7.62" length="middle"/>
<pin name="PAD305" x="20.32" y="-10.16" length="middle"/>
<pin name="PAD306" x="20.32" y="-12.7" length="middle"/>
<pin name="PAD309" x="20.32" y="-15.24" length="middle"/>
<pin name="PAD310" x="20.32" y="-17.78" length="middle"/>
<pin name="PAD313" x="20.32" y="-20.32" length="middle"/>
<pin name="PAD314" x="20.32" y="-22.86" length="middle"/>
<pin name="PAD315" x="20.32" y="-25.4" length="middle"/>
<pin name="PAD316" x="20.32" y="-27.94" length="middle"/>
<pin name="PAD319" x="20.32" y="-30.48" length="middle"/>
<pin name="PAD320" x="20.32" y="-33.02" length="middle"/>
<pin name="PAD323" x="20.32" y="-35.56" length="middle"/>
<pin name="PAD324" x="20.32" y="-38.1" length="middle"/>
<pin name="PAD325" x="20.32" y="-40.64" length="middle"/>
<pin name="PAD326" x="20.32" y="-43.18" length="middle"/>
<pin name="PAD330" x="20.32" y="-45.72" length="middle"/>
<pin name="PAD331" x="20.32" y="-48.26" length="middle"/>
<pin name="PAD335" x="20.32" y="-50.8" length="middle"/>
<pin name="PROGRAM_B" x="20.32" y="-53.34" length="middle" direction="in"/>
<pin name="TCK" x="20.32" y="-55.88" length="middle" direction="in"/>
<pin name="TDI" x="20.32" y="-58.42" length="middle" direction="in"/>
<pin name="TDO" x="20.32" y="-60.96" length="middle" direction="out"/>
<pin name="TMS" x="20.32" y="-63.5" length="middle" direction="in"/>
<pin name="VCCO_0@1" x="20.32" y="-66.04" length="middle" direction="pwr"/>
<pin name="VCCO_0@2" x="20.32" y="-68.58" length="middle" direction="pwr"/>
<pin name="VCCO_1@1" x="20.32" y="-71.12" length="middle" direction="pwr"/>
<pin name="VCCO_1@2" x="20.32" y="-73.66" length="middle" direction="pwr"/>
<pin name="VCCO_2@1" x="45.72" y="81.28" length="middle" direction="pwr"/>
<pin name="VCCO_2@2" x="45.72" y="78.74" length="middle" direction="pwr"/>
<pin name="VCCO_3@1" x="45.72" y="76.2" length="middle" direction="pwr"/>
<pin name="VCCO_3@2" x="45.72" y="73.66" length="middle" direction="pwr"/>
<pin name="VCCO_4@1" x="45.72" y="71.12" length="middle" direction="pwr"/>
<pin name="VCCO_4@2" x="45.72" y="68.58" length="middle" direction="pwr"/>
<pin name="VCCO_5@1" x="45.72" y="66.04" length="middle" direction="pwr"/>
<pin name="VCCO_5@2" x="45.72" y="63.5" length="middle" direction="pwr"/>
<pin name="VCCO_6@1" x="45.72" y="60.96" length="middle" direction="pwr"/>
<pin name="VCCO_6@2" x="45.72" y="58.42" length="middle" direction="pwr"/>
<pin name="VCCO_7@1" x="45.72" y="55.88" length="middle" direction="pwr"/>
<pin name="VCCO_7@2" x="45.72" y="53.34" length="middle" direction="pwr"/>
<pin name="VDD@1" x="45.72" y="50.8" length="middle" direction="pwr"/>
<pin name="VDD@2" x="45.72" y="48.26" length="middle" direction="pwr"/>
<pin name="VDD@3" x="45.72" y="45.72" length="middle" direction="pwr"/>
<pin name="VDD@4" x="45.72" y="43.18" length="middle" direction="pwr"/>
<pin name="VDD@5" x="45.72" y="40.64" length="middle" direction="pwr"/>
<pin name="VDD@6" x="45.72" y="38.1" length="middle" direction="pwr"/>
<pin name="VDD@7" x="45.72" y="35.56" length="middle" direction="pwr"/>
<pin name="VDD@8" x="45.72" y="33.02" length="middle" direction="pwr"/>
<pin name="VDD@9" x="45.72" y="30.48" length="middle" direction="pwr"/>
<pin name="VDD@10" x="45.72" y="27.94" length="middle" direction="pwr"/>
<pin name="VDD@11" x="45.72" y="25.4" length="middle" direction="pwr"/>
<pin name="VDD@12" x="45.72" y="22.86" length="middle" direction="pwr"/>
</symbol>
</symbols>
<devicesets>
<deviceset name="XCV200ES_BG256" prefix="IC" library_version="1">
<description>&lt;b&gt;xcv200es_bg256&lt;/b&gt; &lt;font color="red"&gt;edit this description&lt;/font&gt;&lt;p&gt;
Auto generated by &lt;i&gt;make-symbol-device-package-bsdl.ulp Rev. 26&lt;/i&gt;&lt;br&gt;
Source: xcv200es_bg256.bsd</description>
<gates>
<gate name="G$1" symbol="XCV200ES_BG256" x="0" y="0"/>
</gates>
<devices>
<device name="" package="BG256">
<connects>
<connect gate="G$1" pin="CCLK" pad="B19"/>
<connect gate="G$1" pin="DONE" pad="W19"/>
<connect gate="G$1" pin="DXN" pad="W3"/>
<connect gate="G$1" pin="DXP" pad="V4"/>
<connect gate="G$1" pin="GCLKPAD0" pad="Y11"/>
<connect gate="G$1" pin="GCLKPAD1" pad="Y10"/>
<connect gate="G$1" pin="GCLKPAD2" pad="A10"/>
<connect gate="G$1" pin="GCLKPAD3" pad="B10"/>
<connect gate="G$1" pin="GND@1" pad="L4"/>
<connect gate="G$1" pin="GND@10" pad="D16"/>
<connect gate="G$1" pin="GND@11" pad="K10"/>
<connect gate="G$1" pin="GND@12" pad="J11"/>
<connect gate="G$1" pin="GND@13" pad="C18"/>
<connect gate="G$1" pin="GND@14" pad="D17"/>
<connect gate="G$1" pin="GND@15" pad="L10"/>
<connect gate="G$1" pin="GND@16" pad="K11"/>
<connect gate="G$1" pin="GND@17" pad="J12"/>
<connect gate="G$1" pin="GND@18" pad="E17"/>
<connect gate="G$1" pin="GND@19" pad="M10"/>
<connect gate="G$1" pin="GND@2" pad="J9"/>
<connect gate="G$1" pin="GND@20" pad="L11"/>
<connect gate="G$1" pin="GND@21" pad="K12"/>
<connect gate="G$1" pin="GND@22" pad="M11"/>
<connect gate="G$1" pin="GND@23" pad="L12"/>
<connect gate="G$1" pin="GND@24" pad="M12"/>
<connect gate="G$1" pin="GND@25" pad="J17"/>
<connect gate="G$1" pin="GND@26" pad="K17"/>
<connect gate="G$1" pin="GND@27" pad="L17"/>
<connect gate="G$1" pin="GND@28" pad="M17"/>
<connect gate="G$1" pin="GND@29" pad="U10"/>
<connect gate="G$1" pin="GND@3" pad="L9"/>
<connect gate="G$1" pin="GND@30" pad="C3"/>
<connect gate="G$1" pin="GND@31" pad="U11"/>
<connect gate="G$1" pin="GND@32" pad="U12"/>
<connect gate="G$1" pin="GND@33" pad="E4"/>
<connect gate="G$1" pin="GND@34" pad="U16"/>
<connect gate="G$1" pin="GND@35" pad="T17"/>
<connect gate="G$1" pin="GND@36" pad="U17"/>
<connect gate="G$1" pin="GND@37" pad="V18"/>
<connect gate="G$1" pin="GND@38" pad="K4"/>
<connect gate="G$1" pin="GND@39" pad="M4"/>
<connect gate="G$1" pin="GND@4" pad="D10"/>
<connect gate="G$1" pin="GND@40" pad="K9"/>
<connect gate="G$1" pin="GND@41" pad="M9"/>
<connect gate="G$1" pin="GND@42" pad="U4"/>
<connect gate="G$1" pin="GND@43" pad="U5"/>
<connect gate="G$1" pin="GND@44" pad="U9"/>
<connect gate="G$1" pin="GND@45" pad="D4"/>
<connect gate="G$1" pin="GND@46" pad="D5"/>
<connect gate="G$1" pin="GND@47" pad="D9"/>
<connect gate="G$1" pin="GND@48" pad="J4"/>
<connect gate="G$1" pin="GND@5" pad="D11"/>
<connect gate="G$1" pin="GND@6" pad="D12"/>
<connect gate="G$1" pin="GND@7" pad="T4"/>
<connect gate="G$1" pin="GND@8" pad="V3"/>
<connect gate="G$1" pin="GND@9" pad="J10"/>
<connect gate="G$1" pin="INIT" pad="U18"/>
<connect gate="G$1" pin="M0" pad="Y1"/>
<connect gate="G$1" pin="M1" pad="U3"/>
<connect gate="G$1" pin="M2" pad="W2"/>
<connect gate="G$1" pin="PAD101" pad="E19"/>
<connect gate="G$1" pin="PAD102" pad="D20"/>
<connect gate="G$1" pin="PAD105" pad="F19"/>
<connect gate="G$1" pin="PAD106" pad="E20"/>
<connect gate="G$1" pin="PAD107" pad="G19"/>
<connect gate="G$1" pin="PAD108" pad="F20"/>
<connect gate="G$1" pin="PAD11" pad="C7"/>
<connect gate="G$1" pin="PAD111" pad="G20"/>
<connect gate="G$1" pin="PAD112" pad="H18"/>
<connect gate="G$1" pin="PAD115" pad="H19"/>
<connect gate="G$1" pin="PAD116" pad="H20"/>
<connect gate="G$1" pin="PAD117" pad="J18"/>
<connect gate="G$1" pin="PAD118" pad="J19"/>
<connect gate="G$1" pin="PAD12" pad="C5"/>
<connect gate="G$1" pin="PAD121" pad="J20"/>
<connect gate="G$1" pin="PAD122" pad="K20"/>
<connect gate="G$1" pin="PAD125" pad="K19"/>
<connect gate="G$1" pin="PAD126" pad="K18"/>
<connect gate="G$1" pin="PAD127" pad="L20"/>
<connect gate="G$1" pin="PAD13" pad="B4"/>
<connect gate="G$1" pin="PAD131" pad="L19"/>
<connect gate="G$1" pin="PAD132" pad="M20"/>
<connect gate="G$1" pin="PAD135" pad="M19"/>
<connect gate="G$1" pin="PAD136" pad="M18"/>
<connect gate="G$1" pin="PAD137" pad="N20"/>
<connect gate="G$1" pin="PAD138" pad="N19"/>
<connect gate="G$1" pin="PAD14" pad="A3"/>
<connect gate="G$1" pin="PAD141" pad="N18"/>
<connect gate="G$1" pin="PAD142" pad="P20"/>
<connect gate="G$1" pin="PAD145" pad="R20"/>
<connect gate="G$1" pin="PAD146" pad="P19"/>
<connect gate="G$1" pin="PAD147" pad="T20"/>
<connect gate="G$1" pin="PAD148" pad="R19"/>
<connect gate="G$1" pin="PAD151" pad="U20"/>
<connect gate="G$1" pin="PAD152" pad="T19"/>
<connect gate="G$1" pin="PAD155" pad="R18"/>
<connect gate="G$1" pin="PAD156" pad="V20"/>
<connect gate="G$1" pin="PAD157" pad="U19"/>
<connect gate="G$1" pin="PAD158" pad="T18"/>
<connect gate="G$1" pin="PAD162" pad="P18"/>
<connect gate="G$1" pin="PAD163" pad="W20"/>
<connect gate="G$1" pin="PAD167" pad="V19"/>
<connect gate="G$1" pin="PAD169" pad="V17"/>
<connect gate="G$1" pin="PAD17" pad="C6"/>
<connect gate="G$1" pin="PAD170" pad="W18"/>
<connect gate="G$1" pin="PAD174" pad="Y19"/>
<connect gate="G$1" pin="PAD175" pad="V14"/>
<connect gate="G$1" pin="PAD179" pad="V16"/>
<connect gate="G$1" pin="PAD18" pad="B5"/>
<connect gate="G$1" pin="PAD180" pad="W17"/>
<connect gate="G$1" pin="PAD181" pad="Y18"/>
<connect gate="G$1" pin="PAD182" pad="V15"/>
<connect gate="G$1" pin="PAD185" pad="W16"/>
<connect gate="G$1" pin="PAD186" pad="Y17"/>
<connect gate="G$1" pin="PAD189" pad="W15"/>
<connect gate="G$1" pin="PAD190" pad="Y16"/>
<connect gate="G$1" pin="PAD191" pad="Y15"/>
<connect gate="G$1" pin="PAD192" pad="W14"/>
<connect gate="G$1" pin="PAD195" pad="Y14"/>
<connect gate="G$1" pin="PAD196" pad="V13"/>
<connect gate="G$1" pin="PAD199" pad="W13"/>
<connect gate="G$1" pin="PAD2" pad="C4"/>
<connect gate="G$1" pin="PAD200" pad="Y13"/>
<connect gate="G$1" pin="PAD201" pad="V12"/>
<connect gate="G$1" pin="PAD202" pad="W12"/>
<connect gate="G$1" pin="PAD205" pad="Y12"/>
<connect gate="G$1" pin="PAD206" pad="V11"/>
<connect gate="G$1" pin="PAD209" pad="W11"/>
<connect gate="G$1" pin="PAD21" pad="A4"/>
<connect gate="G$1" pin="PAD215" pad="W10"/>
<connect gate="G$1" pin="PAD216" pad="Y9"/>
<connect gate="G$1" pin="PAD219" pad="W9"/>
<connect gate="G$1" pin="PAD22" pad="B6"/>
<connect gate="G$1" pin="PAD220" pad="V9"/>
<connect gate="G$1" pin="PAD221" pad="Y8"/>
<connect gate="G$1" pin="PAD222" pad="W8"/>
<connect gate="G$1" pin="PAD225" pad="V8"/>
<connect gate="G$1" pin="PAD226" pad="Y7"/>
<connect gate="G$1" pin="PAD229" pad="Y6"/>
<connect gate="G$1" pin="PAD23" pad="A5"/>
<connect gate="G$1" pin="PAD230" pad="W7"/>
<connect gate="G$1" pin="PAD231" pad="Y5"/>
<connect gate="G$1" pin="PAD232" pad="W6"/>
<connect gate="G$1" pin="PAD235" pad="Y4"/>
<connect gate="G$1" pin="PAD236" pad="W5"/>
<connect gate="G$1" pin="PAD239" pad="V6"/>
<connect gate="G$1" pin="PAD24" pad="A6"/>
<connect gate="G$1" pin="PAD240" pad="Y3"/>
<connect gate="G$1" pin="PAD241" pad="W4"/>
<connect gate="G$1" pin="PAD242" pad="V5"/>
<connect gate="G$1" pin="PAD246" pad="V7"/>
<connect gate="G$1" pin="PAD247" pad="Y2"/>
<connect gate="G$1" pin="PAD253" pad="V2"/>
<connect gate="G$1" pin="PAD254" pad="W1"/>
<connect gate="G$1" pin="PAD258" pad="P3"/>
<connect gate="G$1" pin="PAD259" pad="T3"/>
<connect gate="G$1" pin="PAD263" pad="U2"/>
<connect gate="G$1" pin="PAD264" pad="V1"/>
<connect gate="G$1" pin="PAD265" pad="R3"/>
<connect gate="G$1" pin="PAD266" pad="T2"/>
<connect gate="G$1" pin="PAD269" pad="U1"/>
<connect gate="G$1" pin="PAD27" pad="B7"/>
<connect gate="G$1" pin="PAD270" pad="R2"/>
<connect gate="G$1" pin="PAD273" pad="T1"/>
<connect gate="G$1" pin="PAD274" pad="R1"/>
<connect gate="G$1" pin="PAD275" pad="P2"/>
<connect gate="G$1" pin="PAD276" pad="P1"/>
<connect gate="G$1" pin="PAD279" pad="N3"/>
<connect gate="G$1" pin="PAD28" pad="A7"/>
<connect gate="G$1" pin="PAD280" pad="N2"/>
<connect gate="G$1" pin="PAD283" pad="N1"/>
<connect gate="G$1" pin="PAD284" pad="M3"/>
<connect gate="G$1" pin="PAD285" pad="M2"/>
<connect gate="G$1" pin="PAD286" pad="M1"/>
<connect gate="G$1" pin="PAD289" pad="L1"/>
<connect gate="G$1" pin="PAD290" pad="L2"/>
<connect gate="G$1" pin="PAD294" pad="K1"/>
<connect gate="G$1" pin="PAD295" pad="K2"/>
<connect gate="G$1" pin="PAD296" pad="K3"/>
<connect gate="G$1" pin="PAD299" pad="J1"/>
<connect gate="G$1" pin="PAD300" pad="J2"/>
<connect gate="G$1" pin="PAD303" pad="J3"/>
<connect gate="G$1" pin="PAD304" pad="H1"/>
<connect gate="G$1" pin="PAD305" pad="H2"/>
<connect gate="G$1" pin="PAD306" pad="G1"/>
<connect gate="G$1" pin="PAD309" pad="H3"/>
<connect gate="G$1" pin="PAD31" pad="C8"/>
<connect gate="G$1" pin="PAD310" pad="G2"/>
<connect gate="G$1" pin="PAD313" pad="F1"/>
<connect gate="G$1" pin="PAD314" pad="E1"/>
<connect gate="G$1" pin="PAD315" pad="F2"/>
<connect gate="G$1" pin="PAD316" pad="D1"/>
<connect gate="G$1" pin="PAD319" pad="E2"/>
<connect gate="G$1" pin="PAD32" pad="B8"/>
<connect gate="G$1" pin="PAD320" pad="F3"/>
<connect gate="G$1" pin="PAD323" pad="C1"/>
<connect gate="G$1" pin="PAD324" pad="G3"/>
<connect gate="G$1" pin="PAD325" pad="D2"/>
<connect gate="G$1" pin="PAD326" pad="E3"/>
<connect gate="G$1" pin="PAD33" pad="A8"/>
<connect gate="G$1" pin="PAD330" pad="B2"/>
<connect gate="G$1" pin="PAD331" pad="B1"/>
<connect gate="G$1" pin="PAD335" pad="C2"/>
<connect gate="G$1" pin="PAD34" pad="C9"/>
<connect gate="G$1" pin="PAD37" pad="B9"/>
<connect gate="G$1" pin="PAD38" pad="A9"/>
<connect gate="G$1" pin="PAD44" pad="A11"/>
<connect gate="G$1" pin="PAD47" pad="B11"/>
<connect gate="G$1" pin="PAD48" pad="C11"/>
<connect gate="G$1" pin="PAD51" pad="A12"/>
<connect gate="G$1" pin="PAD52" pad="B12"/>
<connect gate="G$1" pin="PAD53" pad="C12"/>
<connect gate="G$1" pin="PAD54" pad="A13"/>
<connect gate="G$1" pin="PAD57" pad="B13"/>
<connect gate="G$1" pin="PAD58" pad="C13"/>
<connect gate="G$1" pin="PAD6" pad="B3"/>
<connect gate="G$1" pin="PAD61" pad="A14"/>
<connect gate="G$1" pin="PAD62" pad="B14"/>
<connect gate="G$1" pin="PAD63" pad="A15"/>
<connect gate="G$1" pin="PAD64" pad="B15"/>
<connect gate="G$1" pin="PAD67" pad="A16"/>
<connect gate="G$1" pin="PAD68" pad="B16"/>
<connect gate="G$1" pin="PAD7" pad="A2"/>
<connect gate="G$1" pin="PAD71" pad="C15"/>
<connect gate="G$1" pin="PAD72" pad="A17"/>
<connect gate="G$1" pin="PAD73" pad="C14"/>
<connect gate="G$1" pin="PAD74" pad="A18"/>
<connect gate="G$1" pin="PAD78" pad="B17"/>
<connect gate="G$1" pin="PAD79" pad="C16"/>
<connect gate="G$1" pin="PAD83" pad="A19"/>
<connect gate="G$1" pin="PAD84" pad="B18"/>
<connect gate="G$1" pin="PAD85" pad="D18"/>
<connect gate="G$1" pin="PAD86" pad="C19"/>
<connect gate="G$1" pin="PAD90" pad="B20"/>
<connect gate="G$1" pin="PAD91" pad="G18"/>
<connect gate="G$1" pin="PAD95" pad="E18"/>
<connect gate="G$1" pin="PAD96" pad="D19"/>
<connect gate="G$1" pin="PAD97" pad="C20"/>
<connect gate="G$1" pin="PAD98" pad="F18"/>
<connect gate="G$1" pin="PROGRAM_B" pad="Y20"/>
<connect gate="G$1" pin="TCK" pad="A1"/>
<connect gate="G$1" pin="TDI" pad="C17"/>
<connect gate="G$1" pin="TDO" pad="A20"/>
<connect gate="G$1" pin="TMS" pad="D3"/>
<connect gate="G$1" pin="VCCO_0@1" pad="D7"/>
<connect gate="G$1" pin="VCCO_0@2" pad="D8"/>
<connect gate="G$1" pin="VCCO_1@1" pad="D13"/>
<connect gate="G$1" pin="VCCO_1@2" pad="D14"/>
<connect gate="G$1" pin="VCCO_2@1" pad="H17"/>
<connect gate="G$1" pin="VCCO_2@2" pad="G17"/>
<connect gate="G$1" pin="VCCO_3@1" pad="P17"/>
<connect gate="G$1" pin="VCCO_3@2" pad="N17"/>
<connect gate="G$1" pin="VCCO_4@1" pad="U13"/>
<connect gate="G$1" pin="VCCO_4@2" pad="U14"/>
<connect gate="G$1" pin="VCCO_5@1" pad="U7"/>
<connect gate="G$1" pin="VCCO_5@2" pad="U8"/>
<connect gate="G$1" pin="VCCO_6@1" pad="N4"/>
<connect gate="G$1" pin="VCCO_6@2" pad="P4"/>
<connect gate="G$1" pin="VCCO_7@1" pad="G4"/>
<connect gate="G$1" pin="VCCO_7@2" pad="H4"/>
<connect gate="G$1" pin="VDD@1" pad="C10"/>
<connect gate="G$1" pin="VDD@10" pad="L18"/>
<connect gate="G$1" pin="VDD@11" pad="F17"/>
<connect gate="G$1" pin="VDD@12" pad="D15"/>
<connect gate="G$1" pin="VDD@2" pad="D6"/>
<connect gate="G$1" pin="VDD@3" pad="F4"/>
<connect gate="G$1" pin="VDD@4" pad="L3"/>
<connect gate="G$1" pin="VDD@5" pad="R4"/>
<connect gate="G$1" pin="VDD@6" pad="U6"/>
<connect gate="G$1" pin="VDD@7" pad="V10"/>
<connect gate="G$1" pin="VDD@8" pad="U15"/>
<connect gate="G$1" pin="VDD@9" pad="R17"/>
</connects>
<technologies>
<technology name="">
<attribute name="MF" value="" constant="no"/>
<attribute name="MPN" value="" constant="no"/>
<attribute name="OC_FARNELL" value="unknown" constant="no"/>
<attribute name="OC_NEWARK" value="unknown" constant="no"/>
</technology>
</technologies>
</device>
</devices>
</deviceset>
</devicesets>
</library>
</libraries>
<attributes>
</attributes>
<variantdefs>
</variantdefs>
<classes>
<class number="0" name="default" width="0" drill="0">
</class>
</classes>
<parts>
<part name="IC1" library="xilinx-xcv" library_urn="urn:adsk.eagle:library:417" deviceset="XCV200ES_BG256" device=""/>
</parts>
<sheets>
<sheet>
<plain>
</plain>
<instances>
<instance part="IC1" gate="G$1" x="96.52" y="17.78" smashed="yes">
<attribute name="NAME" x="40.64" y="104.14" size="1.778" layer="95"/>
<attribute name="VALUE" x="40.64" y="101.6" size="1.778" layer="96"/>
</instance>
</instances>
<busses>
</busses>
<nets>
</nets>
</sheet>
</sheets>
</schematic>
</drawing>
<compatibility>
<note version="8.2" severity="warning">
Since Version 8.2, EAGLE supports online libraries. The ids
of those online libraries will not be understood (or retained)
with this version.
</note>
</compatibility>
</eagle>
